name: 00 - Main CI / CD Pipeline

on:
  Push:
    paths-ignore:
      - '**/*.md
      - '**/*.txt
  workflow_dispatch:

jobs:
  buold:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_id
